--- !ditz.rubyforge.org,2008-03-06/project 
name: bitstream
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: bitstream
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: bitstream-0.1
  status: :released
  release_time: 2011-02-17 15:54:47.301962 Z
  log_events: 
  - - 2011-02-17 15:53:37.477156 Z
    - PHO <pho@cielonegro.org>
    - created
    - The initial release for the bitstream package.
  - - 2011-02-17 15:54:47.302007 Z
    - PHO <pho@cielonegro.org>
    - released
    - I think it's now ready for distribution.
- !ditz.rubyforge.org,2008-03-06/release 
  name: bitstream-0.2
  status: :released
  release_time: 2011-07-08 04:42:50.927075 Z
  log_events: 
  - - 2011-05-12 04:48:10.840483 Z
    - PHO <pho@cielonegro.org>
    - created
    - |-
      Let stream fusion actually work! Without this the entire package makes
      little sense.
  - - 2011-07-08 04:42:50.927113 Z
    - PHO <pho@cielonegro.org>
    - released
    - Done.
- !ditz.rubyforge.org,2008-03-06/release 
  name: bitstream-0.2.0.1
  status: :released
  release_time: 2011-08-26 09:41:10.812918 Z
  log_events: 
  - - 2011-08-26 09:35:21.213249 Z
    - PHO <pho@cielonegro.org>
    - created
    - ""
  - - 2011-08-26 09:41:10.812941 Z
    - PHO <pho@cielonegro.org>
    - released
    - ""
